# Generated by Django 3.2.17 on 2023-02-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=200, null=True)),
                ('studentid', models.CharField(max_length=50, null=True)),
                ('lecturesattended', models.IntegerField(null=True)),
                ('totallectures', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=200, null=True)),
                ('studentid', models.CharField(max_length=50, null=True)),
                ('physicsmark', models.IntegerField(null=True)),
                ('mathematicsmark', models.IntegerField(null=True)),
                ('englishmark', models.IntegerField(null=True)),
                ('kiswahilimark', models.IntegerField(null=True)),
                ('chemistrymark', models.IntegerField(null=True)),
                ('biologymark', models.IntegerField(null=True)),
                ('agriculturemark', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
