# Generated by Django 3.2.17 on 2023-02-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='agriculturemark',
            new_name='agriculture',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='biologymark',
            new_name='biology',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='chemistrymark',
            new_name='chemistry',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='englishmark',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='kiswahilimark',
            new_name='kiswahili',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='mathematicsmark',
            new_name='mathematics',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='physicsmark',
            new_name='physics',
        ),
    ]
