# Generated by Django 3.2.17 on 2023-02-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
    ]
